# -*- coding: utf-8 -*-
"""FTS_TVA_France_Brut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XiZKwrw-MHMBQXg6aqsOX5GWqgpNJyXk
"""



"""# FTS — Recherche TVA manquants (France) — Données brutes Commission

**Objectif** : À partir du fichier brut FTS (Commission européenne), identifier les bénéficiaires français sans numéro TVA et les retrouver via l'API Recherche d'Entreprises (`data.gouv.fr`).

**Règles** :
- Aucune colonne supplémentaire n'est ajoutée au fichier de sortie
- Seule la colonne `VAT number of beneficiary` est mise à jour en place
- Les lignes enrichies sont **colorées en zones** (vert = haute confiance, jaune = confiance moyenne)
- Un rapport Excel séparé détaille chaque recherche

**9 stratégies de recherche** appliquées en cascade :
1. Nom complet + filtre département
2. Nom complet sans filtre géographique
3. Nom principal (partie avant `*`)
4. Sigle/acronyme (partie après `*`)
5. Nom sans suffixes juridiques (SA, SAS, SARL, ASSO…)
6. Mots clés significatifs (4 premiers mots, sans stop words)
7. Nom normalisé (sans accents, sans ponctuation)
8. Nom tronqué (pour noms très longs)
9. Nom + ville

**Scoring sur 5 critères** (nouveau — v2) :
- ① Similarité textuelle : `token_sort_ratio` + `token_set_ratio` + `partial_ratio` conditionnel
- ② Ratio de longueur : pénalité si les noms ont des tailles très différentes
- ③ État administratif : pénalité −35 % si l'entreprise est radiée (SIREN fermé)
- ④ Ville : bonus +5 si correspondance, malus −7 % si contradiction
- ⑤ Département : bonus +3 si même département, malus −4 % sinon

---
**Ordre d'exécution** : Cellule 1 → 2 → 3 → 4 → 5 → 6 → 7
"""

# ═══════════════════════════════════════════════════════════════
# CELLULE 1 — Installation des dépendances
# ═══════════════════════════════════════════════════════════════
!pip install -q rapidfuzz openpyxl xlsxwriter tqdm requests

# ═══════════════════════════════════════════════════════════════
# CELLULE 2 — Imports et configuration
# ═══════════════════════════════════════════════════════════════

import io, time, re, unicodedata
from pathlib import Path
from datetime import datetime

import pandas as pd
import requests
from rapidfuzz import fuzz
from tqdm.notebook import tqdm
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font
from google.colab import files

# ─── Paramètres ajustables ────────────────────────────────────────────────────

SEUIL_SCORE      = 82    # Score minimal (0-100) pour accepter une TVA trouvée
                         # v2 : relevé de 80 → 82 pour réduire les faux positifs

SEUIL_HAUTE_CONF = 92    # Score >= ce seuil → colorié en VERT (haute confiance)
                         # Score [SEUIL_SCORE, SEUIL_HAUTE_CONF[ → colorié en JAUNE

DELAI_API        = 0.15  # Secondes entre deux appels API (rate limit = 7 req/s)
MAX_PAR_REQUETE  = 5     # Nombre de résultats API à comparer par requête

# ─── API ──────────────────────────────────────────────────────────────────────
API_URL = "https://recherche-entreprises.api.gouv.fr/search"

# ─── Couleurs Excel (hex sans #) ──────────────────────────────────────────────
COULEUR_LIGNE_VERTE  = "C6EFCE"
COULEUR_LIGNE_JAUNE  = "FFEB9C"
COULEUR_CELL_VERTE   = "00B050"
COULEUR_CELL_ORANGE  = "FFC000"

print("✅ Configuration chargée")

# ═══════════════════════════════════════════════════════════════
# CELLULE 3 — Fonctions utilitaires, scoring et stratégies
# ═══════════════════════════════════════════════════════════════

# ── Normalisation ─────────────────────────────────────────────────────────────

def _normaliser(texte: str) -> str:
    """Majuscules, sans accents, sans ponctuation — pour la comparaison fuzzy."""
    if not texte:
        return ""
    t = unicodedata.normalize("NFD", str(texte).upper())
    t = "".join(c for c in t if unicodedata.category(c) != "Mn")
    t = re.sub(r"[^\w\s]", " ", t)
    return " ".join(t.split())


# ── Calcul du numéro TVA français depuis le SIREN ─────────────────────────────

def _siren_vers_tva(siren: str) -> str:
    """Formule officielle INSEE : clé = (12 + 3 × (SIREN mod 97)) mod 97"""
    n = int(str(siren).strip())
    cle = (12 + 3 * (n % 97)) % 97
    return f"FR{cle:02d}{siren}"


# ── Entités à exclure de la recherche SIREN ───────────────────────────────────

PATTERNS_EXCLUSION = [
    "NATURAL PERSON", "PERSONNE PRIV", "PRIVATPERSON",
    "ART. 38(7)", "ART 38",
]
ENTITES_SUPRA = [
    "COUNCIL OF EUROPE", "CONSEIL DE L'EUROPE",
    "EUROPEAN SPACE AGENCY", "AGENCE SPATIALE EUROPEENNE",
    "UNITED NATIONS", "NATIONS UNIES",
    "ORGANIZATION FOR ECONOMIC", "ORGANISATION DE COOPERATION",
    "REPUBLIQUE FRANCAISE", "FRENCH REPUBLIC",
]

def _est_exclu(nom: str) -> bool:
    nom_up = str(nom).upper()
    for pat in PATTERNS_EXCLUSION + ENTITES_SUPRA:
        if pat in nom_up:
            return True
    return False


# ── Suppression des suffixes juridiques ───────────────────────────────────────

SUFFIXES_REGEX = [
    r"\bS\.?A\.?S\.?\b", r"\bS\.?A\.?R\.?L\.?\b", r"\bE\.?U\.?R\.?L\.?\b",
    r"\bS\.?N\.?C\.?\b",  r"\bS\.?C\.?A\.?\b",    r"\bS\.?C\.?S\.?\b",
    r"\bS\.?C\.?O\.?P\.?\b", r"\bS\.?C\.?I\.?C\.?\b",
    r"\bG\.?I\.?E\.?\b",  r"\bG\.?I\.?P\.?\b",
    r"\bE\.?P\.?I\.?C\.?\b", r"\bE\.?P\.?A\.?\b",
    r"\bASSOCIATION\b",   r"\bASSOC\.?\b",
    r"\bFONDATION\b",     r"\bFOND\.?\b",
    r"\bCOMMUNE\b",       r"\bSTe?\.?\b",
    r"\bLTD\.?\b",        r"\bGMBH\b",
]

def _supprimer_suffixes(nom: str) -> str:
    result = str(nom).upper()
    for pat in SUFFIXES_REGEX:
        result = re.sub(pat, "", result, flags=re.IGNORECASE)
    result = re.sub(r"\s+", " ", result).strip().strip("-").strip(",").strip()
    return result


# ── Extraction des mots clés ──────────────────────────────────────────────────

STOP_WORDS = {
    "DE", "DU", "DES", "LE", "LA", "LES", "ET", "EN", "AU", "AUX",
    "L", "D", "UN", "UNE", "POUR", "PAR", "SUR", "DANS", "A",
    "THE", "OF", "AND", "FOR", "IN", "TO", "DI", "DEL",
}

def _extraire_mots_cles(nom: str, n: int = 4) -> str:
    mots = re.sub(r"[^\w\s]", " ", str(nom).upper()).split()
    significatifs = [m for m in mots if m not in STOP_WORDS and len(m) > 1]
    return " ".join(significatifs[:n])


# ── Génération des 9 requêtes (multi-stratégies) ──────────────────────────────

def _generer_requetes(nom_brut: str, ville: str = None, cp: str = None) -> list:
    nom = str(nom_brut).strip()
    requetes = []

    requetes.append({"query": nom, "cp": cp, "strategie": "1_NOM_COMPLET_CP"})

    if cp:
        requetes.append({"query": nom, "cp": None, "strategie": "2_NOM_COMPLET"})

    if "*" in nom:
        parties = [p.strip() for p in nom.split("*") if p.strip()]
        nom_principal = max(parties, key=len)
        if nom_principal.upper() != nom.upper():
            requetes.append({"query": nom_principal, "cp": cp, "strategie": "3_NOM_PRINCIPAL"})

    if "*" in nom:
        parties = [p.strip() for p in nom.split("*") if p.strip()]
        sigle = min(parties, key=len)
        if len(sigle) >= 2 and sigle.upper() != nom.upper():
            requetes.append({"query": sigle, "cp": cp, "strategie": "4_SIGLE"})

    sans_suf = _supprimer_suffixes(nom)
    if sans_suf and len(sans_suf) > 4 and sans_suf.upper() != nom.upper():
        requetes.append({"query": sans_suf, "cp": cp, "strategie": "5_SANS_SUFFIXE"})

    mots_cles = _extraire_mots_cles(nom, n=4)
    if mots_cles and len(mots_cles) > 5:
        if not any(r["query"].upper().strip() == mots_cles for r in requetes):
            requetes.append({"query": mots_cles, "cp": cp, "strategie": "6_MOTS_CLES"})

    nom_norm = _normaliser(nom)
    if nom_norm and not any(r["query"].upper() == nom_norm for r in requetes):
        requetes.append({"query": nom_norm, "cp": cp, "strategie": "7_NOM_NORMALISE"})

    if len(nom) > 45:
        tronque = nom[:42].rsplit(" ", 1)[0]
        if len(tronque) > 10:
            requetes.append({"query": tronque, "cp": None, "strategie": "8_NOM_TRONQUE"})

    if ville and str(ville).strip():
        premiers = _extraire_mots_cles(nom, n=2)
        if premiers:
            requetes.append({"query": f"{premiers} {str(ville).strip()}",
                             "cp": None, "strategie": "9_NOM_VILLE"})

    vus, dedup = set(), []
    for r in requetes:
        cle = (r["query"].strip().lower(), r.get("cp"))
        if cle not in vus and r["query"].strip():
            vus.add(cle)
            dedup.append(r)
    return dedup


# ══════════════════════════════════════════════════════════════════════════════
# SCORING V2 — 5 critères combinés
# ══════════════════════════════════════════════════════════════════════════════

def _scorer(ref_norm: str, api_norm: str, ref_ville: str, ref_cp: str,
            api_result: dict) -> tuple:
    """
    Calcule un score combiné (0-100) et retourne (score, audit_lisible).

    Critères appliqués dans l'ordre :

    ① Similarité textuelle
       • token_sort_ratio  : robuste aux permutations de mots
         ex. 'SOLIDARITES INTERNATIONAL' ≡ 'INTERNATIONAL SOLIDARITES' → 100
       • token_set_ratio   : gère les inclusions partielles
         ex. 'ACF' dans 'ACTION CONTRE LA FAIM ACF' → score élevé
       • partial_ratio     : conditionnel — uniquement si ratio longueur ≥ 0.60
         Garde : évite que 'PARIS' (5 cars) matche 'CLUB SPORTIF PARIS NORD' (20 cars)

    ② Ratio de longueur
       Si les deux noms ont des longueurs très différentes (ratio < 0.60) :
       → partial_ratio ignoré + pénalité −10% sur le score textuel
       Raison : un nom très court trouvé dans un nom très long = faux positif probable

    ③ État administratif (champ 'etat_administratif' dans la réponse API)
       • 'A' (actif)  → aucun impact
       • 'C' (cessé)  → pénalité −35% (entreprise radiée, SIREN fermé)
       Raison : accepter le SIREN d'une entreprise fermée crée une TVA invalide

    ④ Validation ville
       Compare la ville du FTS avec 'siege.libelle_commune' de l'API
       • Similarité ≥ 80% → bonus +5
       • Similarité < 35% et score < 95 → malus −7%

    ⑤ Validation département
       Compare les 2 premiers chiffres du code postal FTS vs code postal API
       • Même département → bonus +3
       • Département différent et score < 93 → malus −4%
    """
    if not api_norm:
        return 0, "api_nom_vide"

    audit = []

    # ── ① Similarité textuelle ─────────────────────────────────────────────────
    s_sort = fuzz.token_sort_ratio(ref_norm, api_norm)
    s_set  = fuzz.token_set_ratio(ref_norm, api_norm)
    audit.append(f"sort={s_sort}")
    audit.append(f"set={s_set}")

    # ── ② Ratio de longueur + partial_ratio conditionnel ─────────────────────
    len_ref = max(len(ref_norm.replace(" ", "")), 1)
    len_api = max(len(api_norm.replace(" ", "")), 1)
    ratio_lon = min(len_ref, len_api) / max(len_ref, len_api)

    if ratio_lon >= 0.60:
        # Noms de longueur comparable → partial_ratio fiable
        s_partial = fuzz.partial_ratio(ref_norm, api_norm)
        score = max(s_sort, int(s_set * 0.97), int(s_partial * 0.88))
        audit.append(f"partial={s_partial}→pondéré={int(s_partial*0.88)}")
    else:
        # Grande différence de longueur → partial_ratio non fiable → ignoré + pénalité
        score = int(max(s_sort, int(s_set * 0.97)) * 0.90)
        audit.append(f"partial=ignoré(ratio={ratio_lon:.2f},-10%)")

    # ── ③ État administratif ──────────────────────────────────────────────────
    etat = (api_result.get("etat_administratif") or "").strip().upper()
    if etat == "C":
        score = int(score * 0.65)
        audit.append("RADIÉE(-35%)")
    elif etat == "A":
        audit.append("active✓")
    else:
        audit.append(f"état={etat or '?'}")

    # ── ④ Validation ville ────────────────────────────────────────────────────
    siege       = api_result.get("siege") or {}
    api_cp_raw  = str(siege.get("code_postal", "") or "").strip()
    api_commune = _normaliser(siege.get("libelle_commune", "") or "")

    if ref_ville and api_commune:
        sim_v = fuzz.token_sort_ratio(_normaliser(ref_ville), api_commune)
        if sim_v >= 80:
            score = min(100, score + 5)
            audit.append(f"ville≈+5({api_commune})")
        elif sim_v < 35 and score < 95:
            score = max(0, int(score * 0.93))
            audit.append(f"ville≠-7%({api_commune})")

    # ── ⑤ Validation département ─────────────────────────────────────────────
    api_dept = api_cp_raw[:2] if len(api_cp_raw) >= 2 else ""
    ref_dept = ref_cp[:2]     if ref_cp and len(ref_cp) >= 2 else ""

    if ref_dept and api_dept:
        if ref_dept == api_dept:
            score = min(100, score + 3)
            audit.append(f"dept={ref_dept}+3")
        elif score < 93:
            score = max(0, int(score * 0.96))
            audit.append(f"dept≠({ref_dept}≠{api_dept})-4%")

    return min(100, max(0, score)), " | ".join(audit)


# ── Appel API avec scoring v2 ─────────────────────────────────────────────────

def _appeler_api(query: str, cp: str, nom_reference: str, ville_reference: str,
                 session: requests.Session) -> dict | None:
    """
    Interroge l'API et retourne le meilleur résultat scoré sur 5 critères.
    Retourne None si aucun résultat ou erreur réseau.
    """
    params = {"q": query, "page": 1, "per_page": MAX_PAR_REQUETE}
    if cp and str(cp).strip():
        dept = str(cp).strip()
        dept = dept[:3] if dept[:2] in ("97", "98") else dept[:2]
        if dept.isdigit():
            params["departement"] = dept

    try:
        time.sleep(DELAI_API)
        r = session.get(API_URL, params=params, timeout=12)
        r.raise_for_status()
        resultats = r.json().get("results", [])
    except Exception:
        return None

    if not resultats:
        return None

    ref_norm  = _normaliser(nom_reference)
    ref_ville = _normaliser(ville_reference or "")
    meilleur  = None
    meilleur_score = -1

    for res in resultats:
        siren = str(res.get("siren", "")).strip()
        if not siren:
            continue

        # Tous les noms disponibles pour ce SIREN
        noms_candidats = [res.get("nom_complet", "")]
        for champ in ["nom_raison_sociale", "sigle"]:
            val = res.get(champ, "")
            if val:
                noms_candidats.append(val)

        for nom_api in noms_candidats:
            if not nom_api:
                continue
            api_norm = _normaliser(nom_api)
            score, detail = _scorer(ref_norm, api_norm, ref_ville, cp, res)

            if score > meilleur_score:
                meilleur_score = score
                meilleur = {
                    "siren":   siren,
                    "nom_api": nom_api,
                    "score":   score,
                    "detail":  detail,
                }

    if meilleur and meilleur["siren"]:
        meilleur["tva"] = _siren_vers_tva(meilleur["siren"])

    return meilleur


# ── Moteur principal : 9 stratégies en cascade ────────────────────────────────

def rechercher_tva(nom_brut: str, ville: str, cp: str,
                   session: requests.Session, seuil: int) -> dict:
    """
    Tente de retrouver la TVA française d'un bénéficiaire via 9 stratégies.
    S'arrête à la première stratégie dont le score v2 ≥ seuil.
    """
    if _est_exclu(nom_brut):
        return {"statut": "EXCLU", "strategie": "", "siren": "",
                "tva": "", "nom_api": "", "score": 0, "detail": ""}

    requetes = _generer_requetes(nom_brut, ville, cp)
    meilleur_global = None

    for req in requetes:
        res = _appeler_api(req["query"], req["cp"], nom_brut, ville, session)
        if res:
            if meilleur_global is None or res["score"] > meilleur_global["score"]:
                meilleur_global = {**res, "strategie": req["strategie"]}
            if res["score"] >= seuil:
                return {
                    "statut":    "TROUVE",
                    "strategie": req["strategie"],
                    "siren":     res["siren"],
                    "tva":       res["tva"],
                    "nom_api":   res["nom_api"],
                    "score":     res["score"],
                    "detail":    res.get("detail", ""),
                }

    return {
        "statut":    "NON_TROUVE",
        "strategie": meilleur_global.get("strategie", "") if meilleur_global else "",
        "siren":     "",
        "tva":       "",
        "nom_api":   meilleur_global.get("nom_api", "") if meilleur_global else "",
        "score":     meilleur_global.get("score", 0)    if meilleur_global else 0,
        "detail":    meilleur_global.get("detail", "")  if meilleur_global else "",
    }


print("✅ Scoring v2 chargé (5 critères : similarité + longueur + statut + ville + département)")

# ═══════════════════════════════════════════════════════════════
# CELLULE 4 — Enrichissement + détection des colonnes
# ═══════════════════════════════════════════════════════════════

def detecter_colonnes(df: pd.DataFrame) -> dict:
    def chercher(*mots_cles):
        for mot in mots_cles:
            for c in df.columns:
                if mot.lower() in c.lower():
                    return c
        return None

    cols = {
        "tva":   chercher("vat number", "vat_number", "tva", "numero tva"),
        "nom":   chercher("name of beneficiary", "beneficiary name", "nom benefi", "nom_benef"),
        "pays":  chercher("beneficiary country", "country", "pays"),
        "cp":    chercher("postal code", "code postal", "zip", "postcode"),
        "ville": chercher("city", "ville", "locality", "localite"),
    }

    manquantes = [k for k in ("tva", "nom", "pays") if cols[k] is None]
    if manquantes:
        raise ValueError(
            f"❌ Colonnes obligatoires introuvables : {manquantes}\n"
            f"   Colonnes disponibles : {list(df.columns)}"
        )

    print("📌 Colonnes détectées :")
    for k, v in cols.items():
        print(f"   {'✅' if v else '⚠️ '} {k:8s} → {v or 'non trouvé (optionnel)'}")
    return cols


def enrichir_france(df: pd.DataFrame, colonnes: dict, seuil: int = SEUIL_SCORE) -> tuple:
    col_tva   = colonnes["tva"]
    col_nom   = colonnes["nom"]
    col_pays  = colonnes["pays"]
    col_cp    = colonnes.get("cp")
    col_ville = colonnes.get("ville")

    mask_fr = df[col_pays].str.strip().str.lower().isin(["france", "fr"])
    print(f"🇫🇷  {mask_fr.sum():,} lignes France détectées")

    mask_manquant = mask_fr & (
        df[col_tva].isna()
        | df[col_tva].str.strip().isin(["-", "", "nan", "NaN", "N/A", "n/a"])
    )
    n_manquants = mask_manquant.sum()
    print(f"⚠️   {n_manquants:,} TVA manquants à rechercher")

    if n_manquants == 0:
        print("✅ Aucun TVA manquant")
        return df.copy(), [], {}

    cols_uniques = [col_nom]
    if col_cp:    cols_uniques.append(col_cp)
    if col_ville: cols_uniques.append(col_ville)

    benef_uniques = (
        df.loc[mask_manquant, cols_uniques]
          .drop_duplicates(subset=[col_nom])
          .reset_index(drop=True)
    )
    n_uniques = len(benef_uniques)
    print(f"📋 {n_uniques:,} bénéficiaires uniques à interroger")
    duree_min = int(n_uniques * DELAI_API * 1.2)
    duree_max = int(n_uniques * DELAI_API * 5)
    print(f"⏱️   Durée estimée : {duree_min}s – {duree_max}s\n")

    session = requests.Session()
    session.headers.update({"User-Agent": "FTS-TVA-Recherche/2.0"})

    rapport, cache = [], {}

    for _, row in tqdm(benef_uniques.iterrows(), total=n_uniques, desc="Recherche TVA"):
        nom   = str(row[col_nom]).strip()
        cp    = str(row[col_cp]).strip()    if col_cp    and pd.notna(row.get(col_cp))    else None
        ville = str(row[col_ville]).strip() if col_ville and pd.notna(row.get(col_ville)) else None

        res = rechercher_tva(nom, ville, cp, session, seuil)
        cache[nom] = res

        rapport.append({
            "Nom_FTS":      nom,
            "Statut":       res["statut"],
            "Strategie":    res["strategie"],
            "SIREN":        res["siren"],
            "TVA_Trouvee":  res["tva"],
            "Nom_API":      res["nom_api"],
            "Score":        res["score"],
            "Detail_Score": res.get("detail", ""),   # audit des 5 critères
        })

    df_out = df.copy()
    updated_rows = {}

    for idx in df_out[mask_manquant].index:
        nom = str(df_out.at[idx, col_nom]).strip()
        res = cache.get(nom)
        if res and res["statut"] == "TROUVE" and res["tva"]:
            df_out.at[idx, col_tva] = res["tva"]
            updated_rows[idx] = res["score"]

    n_trouves = len(updated_rows)
    taux = n_trouves / n_manquants * 100 if n_manquants > 0 else 0
    print(f"\n🎯 {n_trouves:,} / {n_manquants:,} TVA retrouvés ({taux:.1f}%)")
    n_haute = sum(1 for s in updated_rows.values() if s >= SEUIL_HAUTE_CONF)
    print(f"   🟢 Haute confiance (≥{SEUIL_HAUTE_CONF}) : {n_haute:,}")
    print(f"   🟡 Confiance moyenne ({seuil}–{SEUIL_HAUTE_CONF-1}) : {n_trouves - n_haute:,}")

    return df_out, rapport, updated_rows


print("✅ Fonctions d'enrichissement chargées")

# ═══════════════════════════════════════════════════════════════
# CELLULE 5 — Fonctions d'export (fichier coloré + rapport)
# ═══════════════════════════════════════════════════════════════

def exporter_excel_colore(df: pd.DataFrame, updated_rows: dict, nom_fichier: str) -> None:
    print(f"📊 Export Excel : {nom_fichier} ({len(df):,} lignes)...")
    df.to_excel(nom_fichier, index=False, sheet_name="DATASET", engine="openpyxl")

    wb = load_workbook(nom_fichier)
    ws = wb.active
    ws.title = "DATASET"

    col_tva_nom = next((c for c in df.columns if "vat" in c.lower() or "tva" in c.lower()), None)
    col_tva_idx = list(df.columns).index(col_tva_nom) + 1 if col_tva_nom else None

    fill_verte  = PatternFill(start_color=COULEUR_LIGNE_VERTE, fill_type="solid")
    fill_jaune  = PatternFill(start_color=COULEUR_LIGNE_JAUNE, fill_type="solid")
    fill_cv     = PatternFill(start_color=COULEUR_CELL_VERTE,  fill_type="solid")
    fill_co     = PatternFill(start_color=COULEUR_CELL_ORANGE, fill_type="solid")
    font_blanc  = Font(bold=True, color="FFFFFF")
    n_cols = len(df.columns)

    for idx, score in updated_rows.items():
        row_excel = idx + 2
        haute = score >= SEUIL_HAUTE_CONF
        fill  = fill_verte if haute else fill_jaune
        for c in range(1, n_cols + 1):
            ws.cell(row=row_excel, column=c).fill = fill
        if col_tva_idx:
            cell = ws.cell(row=row_excel, column=col_tva_idx)
            cell.fill = fill_cv if haute else fill_co
            cell.font = font_blanc

    if col_tva_idx:
        hdr = ws.cell(row=1, column=col_tva_idx)
        hdr.fill = PatternFill(start_color="4472C4", fill_type="solid")
        hdr.font = Font(bold=True, color="FFFFFF")

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    wb.save(nom_fichier)
    print(f"   ✅ {len(updated_rows):,} lignes colorées → {nom_fichier}")


def _col_lettre(n: int) -> str:
    s = ""
    while n > 0:
        n, r = divmod(n - 1, 26)
        s = chr(65 + r) + s
    return s


def generer_rapport(rapport: list, nom_fichier: str) -> None:
    if not rapport:
        print("⚠️  Rapport vide")
        return

    print(f"📋 Génération rapport : {nom_fichier}...")
    df_rap = pd.DataFrame(rapport)

    with pd.ExcelWriter(nom_fichier, engine="xlsxwriter") as writer:
        df_rap.to_excel(writer, index=False, sheet_name="Résultats_TVA")
        wb = writer.book
        ws = writer.sheets["Résultats_TVA"]
        n = len(df_rap)

        fmt_hdr    = wb.add_format({"bold": True, "bg_color": "#4472C4",
                                    "font_color": "#FFFFFF", "border": 1,
                                    "text_wrap": True, "valign": "vcenter"})
        fmt_trouve = wb.add_format({"bg_color": "#C6EFCE"})
        fmt_non    = wb.add_format({"bg_color": "#FFC7CE"})
        fmt_exclu  = wb.add_format({"bg_color": "#D9D9D9"})

        for i, col in enumerate(df_rap.columns):
            ws.write(0, i, col, fmt_hdr)

        idx_statut     = list(df_rap.columns).index("Statut")
        lettre_statut  = _col_lettre(idx_statut + 1)
        n_cols = len(df_rap.columns) - 1

        for statut, fmt in [("TROUVE", fmt_trouve), ("NON_TROUVE", fmt_non), ("EXCLU", fmt_exclu)]:
            ws.conditional_format(1, 0, n, n_cols, {
                "type": "formula",
                "criteria": f'=${lettre_statut}2="{statut}"',
                "format": fmt,
            })

        ws.set_row(0, 30)
        ws.freeze_panes(1, 0)
        ws.autofilter(0, 0, n, n_cols)
        ws.set_column(0, 0, 60)   # Nom_FTS
        ws.set_column(1, 1, 14)   # Statut
        ws.set_column(2, 2, 26)   # Strategie
        ws.set_column(3, 3, 14)   # SIREN
        ws.set_column(4, 4, 18)   # TVA_Trouvee
        ws.set_column(5, 5, 50)   # Nom_API
        ws.set_column(6, 6, 8)    # Score
        ws.set_column(7, 7, 80)   # Detail_Score — audit des 5 critères

        # Onglet résumé
        resume_statut = df_rap["Statut"].value_counts().reset_index()
        resume_statut.columns = ["Statut", "Nombre"]
        resume_statut["Taux (%)"] = (resume_statut["Nombre"] / len(df_rap) * 100).round(1)

        resume_strat = (
            df_rap[df_rap["Statut"] == "TROUVE"]["Strategie"]
            .value_counts().reset_index()
        )
        if not resume_strat.empty:
            resume_strat.columns = ["Stratégie gagnante", "Nombre"]

        resume_statut.to_excel(writer, index=False, sheet_name="Résumé", startrow=0)
        if not resume_strat.empty:
            resume_strat.to_excel(writer, index=False, sheet_name="Résumé",
                                  startrow=len(resume_statut) + 3)

        ws_res = writer.sheets["Résumé"]
        ws_res.set_column(0, 0, 30)
        ws_res.set_column(1, 2, 15)

    print(f"   ✅ Rapport : {len(df_rap)} bénéficiaires — {nom_fichier}")
    print()
    print("  Résumé par statut :")
    for _, row in resume_statut.iterrows():
        print(f"   {row['Statut']:15s} : {int(row['Nombre']):4d}  ({row['Taux (%)']:.1f}%)")
    if not resume_strat.empty:
        print()
        print("  TVA trouvés par stratégie :")
        for _, row in resume_strat.iterrows():
            print(f"   {row['Stratégie gagnante']:26s} : {int(row['Nombre']):4d}")


print("✅ Fonctions d'export chargées")

"""---
## Étape 1 — Charger le fichier brut FTS

Cliquez sur **Choisir des fichiers** et sélectionnez le fichier Excel (`.xlsx`) ou CSV (`.csv`) téléchargé depuis le portail de la Commission européenne.

> ⚠️ Il peut s'agir d'un fichier annuel (`2024_FTS_dataset_en.xlsx`) ou consolidé multi-années.
"""

# ═══════════════════════════════════════════════════════════════
# CELLULE 6 — Upload du fichier brut FTS
# ═══════════════════════════════════════════════════════════════

print("📂 Sélectionnez le fichier FTS brut (Commission européenne)")
print("   Formats acceptés : .xlsx  .xls  .csv")
print()

uploaded = files.upload()

if not uploaded:
    raise ValueError("❌ Aucun fichier chargé — relancez cette cellule")

nom_fichier_input = list(uploaded.keys())[0]
contenu = uploaded[nom_fichier_input]
print(f"\n✅ Fichier reçu : {nom_fichier_input} ({len(contenu)/1024/1024:.1f} Mo)")

if nom_fichier_input.lower().endswith(".csv"):
    df_brut = None
    for enc in ["utf-8", "latin-1", "utf-8-sig"]:
        for sep in [",", ";", "\t"]:
            try:
                df_brut = pd.read_csv(io.BytesIO(contenu), sep=sep, dtype=str, encoding=enc)
                if len(df_brut.columns) >= 5:
                    print(f"   Encodage: {enc}, séparateur: '{sep}'")
                    break
            except Exception:
                pass
        if df_brut is not None and len(df_brut.columns) >= 5:
            break
    if df_brut is None:
        raise ValueError("❌ Impossible de lire le CSV")
else:
    xl = pd.ExcelFile(io.BytesIO(contenu))
    print(f"   Onglets : {xl.sheet_names}")
    feuille = "DATASET" if "DATASET" in xl.sheet_names else xl.sheet_names[0]
    print(f"   Onglet sélectionné : '{feuille}'")
    df_brut = pd.read_excel(io.BytesIO(contenu), sheet_name=feuille, dtype=str, engine="openpyxl")

print(f"\n📊 {len(df_brut):,} lignes × {len(df_brut.columns)} colonnes chargées\n")

def detecter_colonnes(df: pd.DataFrame) -> dict:
    def chercher(*mots_cles):
        for mot in mots_cles:
            for c in df.columns:
                # Convert column name to string before calling .lower()
                if mot.lower() in str(c).lower():
                    return c
        return None

    cols = {
        "tva":   chercher("vat number", "vat_number", "tva", "numero tva"),
        "nom":   chercher("name of beneficiary", "beneficiary name", "nom benefi", "nom_benef"),
        "pays":  chercher("beneficiary country", "country", "pays"),
        "cp":    chercher("postal code", "code postal", "zip", "postcode"),
        "ville": chercher("city", "ville", "locality", "localite"),
    }

    manquantes = [k for k in ("tva", "nom", "pays") if cols[k] is None]
    if manquantes:
        raise ValueError(
            f"❌ Colonnes obligatoires introuvables : {manquantes}\n"
            f"   Colonnes disponibles : {list(df.columns)}"
        )

    print("📌 Colonnes détectées :")
    for k, v in cols.items():
        print(f"   {'✅' if v else '⚠️ '} {k:8s} → {v or 'non trouvé (optionnel)'}")
    return cols


colonnes = detecter_colonnes(df_brut)

col_tva = colonnes["tva"]
vc = df_brut[col_tva].str.strip().value_counts().head(5)
print(f"\n📌 Aperçu des valeurs dans '{col_tva}' (top 5) :")
for val, cnt in vc.items():
    print(f"   {str(val):30s} → {cnt:,} occurrences")

"""---
## Étape 2 — Recherche des TVA manquants

Le scoring **v2** applique 5 critères pour chaque résultat API :

| Critère | Description | Effet |
|---|---|---|
| ① Similarité | `token_sort` + `token_set` + `partial` conditionnel | Score de base |
| ② Longueur | Si noms très différents en taille → `partial` ignoré | Pénalité −10% |
| ③ Statut | Entreprise radiée (SIREN fermé) | Pénalité −35% |
| ④ Ville | Comparaison avec `siege.libelle_commune` | ±5 pts |
| ⑤ Département | 2 premiers chiffres du code postal | ±3 pts |

> La colonne `Detail_Score` dans le rapport explique chaque décision, critère par critère.
"""

# ═══════════════════════════════════════════════════════════════
# CELLULE 7 — Enrichissement TVA + export des résultats
# ═══════════════════════════════════════════════════════════════

print("=" * 60)
print("  RECHERCHE TVA MANQUANTS — FRANCE  (scoring v2)")
print(f"  Seuil d'acceptation : {SEUIL_SCORE}/100")
print(f"  Haute confiance     : {SEUIL_HAUTE_CONF}/100")
print("=" * 60)
print()

df_enrichi, rapport, updated_rows = enrichir_france(df_brut, colonnes, seuil=SEUIL_SCORE)

horodatage  = datetime.now().strftime("%Y%m%d_%H%M")
base_nom    = Path(nom_fichier_input).stem
nom_sortie  = f"{base_nom}_TVA_ENRICHI_{horodatage}.xlsx"
nom_rapport = f"{base_nom}_RAPPORT_TVA_{horodatage}.xlsx"

print()
print("=" * 60)

if updated_rows:
    exporter_excel_colore(df_enrichi, updated_rows, nom_sortie)
else:
    df_enrichi.to_excel(nom_sortie, index=False, sheet_name="DATASET", engine="openpyxl")
    print(f"📊 Fichier exporté (sans modification) : {nom_sortie}")

generer_rapport(rapport, nom_rapport)

print()
print("=" * 60)
print("⬇️  Téléchargement des fichiers...")
files.download(nom_sortie)
files.download(nom_rapport)

print()
print("✅ TERMINÉ")
print(f"   📄 Fichier enrichi : {nom_sortie}")
print(f"   📋 Rapport         : {nom_rapport}")